work_dir: ./work_dir/pose-audio/first_run

# feeder
feeder: st_gcn.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ./data/Kinetics/kinetics-skeleton/train_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/train_label.pkl
val_feeder_args:
  data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl
# test_feeder_args:
#   data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
#   label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 400            # not required
  channel: 3
  window_size: 150
  num_person: 2
  num_point: 18
  dropout: 0
  graph: st_gcn.graph.Kinetics
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True

# #optim
# weight_decay: 0.0001
# base_lr: 0.1
# step: [20, 30, 40, 50]

# training
device: 0
batch_size: 256
val_batch_size: 256
# num_epoch: 60
# nesterov: True
#

phase: train
weights: ./model/kinetics-st_gcn.pt


# soundnet
model_soundnet: soundnet.net.SOUNDNET
device_soundnet: 1

# finetuning
finetune_device: 0
finetune_step: [20, 30, 40, 50]
finetune_save_interval: 10
finetune_eval_interval: 2
finetune_num_epoch: 60

# loss
loss: cosine